//
// Generated file, do not edit! Created by opp_msgtool 6.3 from messages.msg.
//

#ifndef __MESSAGES_M_H
#define __MESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class LeaderMsg;
class BitMsg;
class LeaderAnnouncement;
/**
 * Class generated from <tt>messages.msg:16</tt> by opp_msgtool.
 * <pre>
 * // Leader message for arbitrary network election
 * packet LeaderMsg
 * {
 *     int senderId;
 *     int leaderValue;
 *     int roundNum;
 * }
 * </pre>
 */
class LeaderMsg : public ::omnetpp::cPacket
{
  protected:
    int senderId = 0;
    int leaderValue = 0;
    int roundNum = 0;

  private:
    void copy(const LeaderMsg& other);

  protected:
    bool operator==(const LeaderMsg&) = delete;

  public:
    LeaderMsg(const char *name=nullptr, short kind=0);
    LeaderMsg(const LeaderMsg& other);
    virtual ~LeaderMsg();
    LeaderMsg& operator=(const LeaderMsg& other);
    virtual LeaderMsg *dup() const override {return new LeaderMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);

    virtual int getLeaderValue() const;
    virtual void setLeaderValue(int leaderValue);

    virtual int getRoundNum() const;
    virtual void setRoundNum(int roundNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LeaderMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LeaderMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>messages.msg:23</tt> by opp_msgtool.
 * <pre>
 * // Bit message for anonymous network election
 * packet BitMsg
 * {
 *     int senderId;
 *     int bitValue;
 *     int roundNum;
 *     bool isActive;
 * }
 * </pre>
 */
class BitMsg : public ::omnetpp::cPacket
{
  protected:
    int senderId = 0;
    int bitValue = 0;
    int roundNum = 0;
    bool isActive_ = false;

  private:
    void copy(const BitMsg& other);

  protected:
    bool operator==(const BitMsg&) = delete;

  public:
    BitMsg(const char *name=nullptr, short kind=0);
    BitMsg(const BitMsg& other);
    virtual ~BitMsg();
    BitMsg& operator=(const BitMsg& other);
    virtual BitMsg *dup() const override {return new BitMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);

    virtual int getBitValue() const;
    virtual void setBitValue(int bitValue);

    virtual int getRoundNum() const;
    virtual void setRoundNum(int roundNum);

    virtual bool isActive() const;
    virtual void setIsActive(bool isActive);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BitMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BitMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>messages.msg:31</tt> by opp_msgtool.
 * <pre>
 * // Leader announcement message
 * packet LeaderAnnouncement
 * {
 *     int leaderId;
 * }
 * </pre>
 */
class LeaderAnnouncement : public ::omnetpp::cPacket
{
  protected:
    int leaderId = 0;

  private:
    void copy(const LeaderAnnouncement& other);

  protected:
    bool operator==(const LeaderAnnouncement&) = delete;

  public:
    LeaderAnnouncement(const char *name=nullptr, short kind=0);
    LeaderAnnouncement(const LeaderAnnouncement& other);
    virtual ~LeaderAnnouncement();
    LeaderAnnouncement& operator=(const LeaderAnnouncement& other);
    virtual LeaderAnnouncement *dup() const override {return new LeaderAnnouncement(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getLeaderId() const;
    virtual void setLeaderId(int leaderId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LeaderAnnouncement& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LeaderAnnouncement& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline LeaderMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<LeaderMsg*>(ptr.get<cObject>()); }
template<> inline BitMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<BitMsg*>(ptr.get<cObject>()); }
template<> inline LeaderAnnouncement *fromAnyPtr(any_ptr ptr) { return check_and_cast<LeaderAnnouncement*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGES_M_H

